import { BankDefinition } from '../types';

export const INDIAN_BANKS: BankDefinition[] = [
  {
    id: 'hdfc',
    name: 'HDFC Bank',
    shortName: 'HDFC',
    senderPatterns: [/HDFCBK/i, /HDFCBN/i, /HDFCTP/i, /HDFCSMS/i, /^HDFC/i, /-HDFCBK$/i],
    messagePatterns: [/HDFC Bank/i, /HDFC/i],
    color: '#004B8D',
    isActive: true,
  },
  {
    id: 'sbi',
    name: 'State Bank of India',
    shortName: 'SBI',
    senderPatterns: [/SBIBNK/i, /SBIINB/i, /SBIPSG/i, /SBIUPI/i, /^SBI/i, /-SBIBNK$/i],
    messagePatterns: [/State Bank of India/i, /SBI/i],
    color: '#280071',
    isActive: true,
  },
  {
    id: 'icici',
    name: 'ICICI Bank',
    shortName: 'ICICI',
    senderPatterns: [/ICICIB/i, /ICICIT/i, /ICICIS/i, /^ICICI/i, /-ICICIB$/i],
    messagePatterns: [/ICICI Bank/i, /ICICI/i],
    color: '#F37021',
    isActive: true,
  },
  {
    id: 'axis',
    name: 'Axis Bank',
    shortName: 'Axis',
    senderPatterns: [/AXISBK/i, /AXISBN/i, /^AXIS/i, /-AXISBK$/i],
    messagePatterns: [/\bAxis Bank\b/i, /\bAxis\b/i],
    color: '#971237',
    isActive: true,
  },
  {
    id: 'kotak',
    name: 'Kotak Mahindra Bank',
    shortName: 'Kotak',
    senderPatterns: [/KOTAKB/i, /KOTAKK/i, /^KOTAK/i, /-KOTAKB$/i],
    messagePatterns: [/Kotak Mahindra Bank/i, /Kotak Bank/i, /Kotak/i],
    color: '#ED1C24',
    isActive: true,
  },
  {
    id: 'canara',
    name: 'Canara Bank',
    shortName: 'Canara',
    senderPatterns: [/CANBNK/i, /CNRBK/i, /CANARA/i, /[A-Z]{2}-CANBNK/i, /[A-Z]{2}-CNRBK/i],
    messagePatterns: [/Canara Bank/i, /Canara/i],
    color: '#FFB800',
    isActive: true,
  },
  {
    id: 'bob',
    name: 'Bank of Baroda',
    shortName: 'BOB',
    senderPatterns: [/BOBBK/i, /BARODB/i, /BOBSMS/i, /BOBTXN/i, /BOB/i, /[A-Z]{2}-BOB/i],
    messagePatterns: [/Bank of Baroda/i, /BOB/i, /Baroda/i],
    color: '#F26522',
    isActive: true,
  },
  {
    id: 'pnb',
    name: 'Punjab National Bank',
    shortName: 'PNB',
    senderPatterns: [/PNBSMS/i, /PNBBK/i, /^PNB/i],
    messagePatterns: [/Punjab National Bank/i, /PNB/i],
    color: '#A20A3C',
    isActive: true,
  },
  {
    id: 'union',
    name: 'Union Bank of India',
    shortName: 'Union',
    senderPatterns: [/UBINOI/i, /UNIONB/i, /^UNION/i],
    messagePatterns: [/Union Bank of India/i, /Union Bank/i],
    color: '#0054A6',
    isActive: true,
  },
  {
    id: 'idfc',
    name: 'IDFC FIRST Bank',
    shortName: 'IDFC FIRST',
    senderPatterns: [/IDFCFB/i, /IDFCBK/i, /^IDFC/i],
    messagePatterns: [/IDFC FIRST Bank/i, /IDFC Bank/i, /IDFC/i],
    color: '#991B1E',
    isActive: true,
  },
  {
    id: 'indusind',
    name: 'IndusInd Bank',
    shortName: 'IndusInd',
    senderPatterns: [/INDUSB/i, /INDUSI/i, /^INDUS/i],
    messagePatterns: [/IndusInd Bank/i, /IndusInd/i],
    color: '#65000B',
    isActive: true,
  },
  {
    id: 'federal',
    name: 'Federal Bank',
    shortName: 'Federal',
    senderPatterns: [/FEDBNK/i, /FEDERAL/i, /^FED/i],
    messagePatterns: [/Federal Bank/i, /Federal/i],
    color: '#00427A',
    isActive: true,
  },
  {
    id: 'yes',
    name: 'Yes Bank',
    shortName: 'YES',
    senderPatterns: [/YESBNK/i, /YESBANK/i, /^YES/i],
    messagePatterns: [/Yes Bank/i, /YES/i],
    color: '#005B9C',
    isActive: true,
  },
  {
    id: 'indian',
    name: 'Indian Bank',
    shortName: 'Indian Bank',
    senderPatterns: [/INDBNK/i, /INDIANB/i],
    messagePatterns: [/Indian Bank/i],
    color: '#003B73',
    isActive: true,
  },
  {
    id: 'boi',
    name: 'Bank of India',
    shortName: 'BOI',
    senderPatterns: [/BOISMS/i, /BOIBNK/i],
    messagePatterns: [/Bank of India/i, /BOI/i],
    color: '#E31B23',
    isActive: true,
  },
  {
    id: 'au',
    name: 'AU Small Finance Bank',
    shortName: 'AU Bank',
    senderPatterns: [/AUBANK/i, /AUSFBK/i],
    messagePatterns: [/AU Small Finance Bank/i, /AU Bank/i],
    color: '#E85F24',
    isActive: true,
  },
];
