import { BankDefinition } from '../types';

export const INDIAN_BANKS: BankDefinition[] = [
  {
    id: 'bob',
    name: 'Bank of Baroda',
    shortName: 'BOB',
    senderPatterns: [/BOBTXN/i, /BOBSMS/i, /BARODB/i, /BOBALT/i, /BOBBK/i, /BOB/i, /[A-Z]{2}-BOB/i, /[A-Z]{2}-BAROD/i],
    messagePatterns: [/Bank of Baroda/i, /\bBOB\b/i, /Baroda/i, /bob World/i, /Baroda M-Connect/i, /barodampay/i],
    color: '#F26522',
    isActive: true,
  },
  {
    id: 'canara',
    name: 'Canara Bank',
    shortName: 'Canara',
    senderPatterns: [/CANBNK/i, /CNRBK/i, /CANARA/i, /[A-Z]{2}-CANBNK/i, /[A-Z]{2}-CNRBK/i, /[A-Z]{2}-CANARA/i],
    messagePatterns: [/Canara Bank/i, /\bCanara\b/i, /CANDI\b/i, /cnrb/i],
    color: '#FFB800',
    isActive: true,
  },
  {
    id: 'hdfc',
    name: 'HDFC Bank',
    shortName: 'HDFC',
    senderPatterns: [/HDFCBK/i, /HDFCBN/i, /HDFCTP/i, /HDFCSMS/i, /^HDFC/i, /-HDFCBK$/i, /[A-Z]{2}-HDFC/i],
    messagePatterns: [/HDFC Bank/i, /\bHDFC\b/i, /PayZapp/i, /okhdfcbank/i, /hdfcbank/i],
    color: '#004B8D',
    isActive: true,
  },
  {
    id: 'sbi',
    name: 'State Bank of India',
    shortName: 'SBI',
    senderPatterns: [/SBIBNK/i, /SBIINB/i, /SBIPSG/i, /SBIUPI/i, /SBIPAY/i, /^SBI/i, /-SBIBNK$/i, /[A-Z]{2}-SBI/i],
    messagePatterns: [/State Bank of India/i, /\bSBI\b/i, /YONO/i, /oksbi/i, /sbiupi/i],
    color: '#280071',
    isActive: true,
  },
  {
    id: 'icici',
    name: 'ICICI Bank',
    shortName: 'ICICI',
    senderPatterns: [/ICICIB/i, /ICICIT/i, /ICICIS/i, /^ICICI/i, /-ICICIB$/i, /[A-Z]{2}-ICICI/i],
    messagePatterns: [/ICICI Bank/i, /\bICICI\b/i, /iMobile/i, /okicici/i],
    color: '#F37021',
    isActive: true,
  },
  {
    id: 'axis',
    name: 'Axis Bank',
    shortName: 'Axis',
    senderPatterns: [/AXISBK/i, /AXISBN/i, /^AXIS/i, /-AXISBK$/i, /[A-Z]{2}-AXIS/i],
    messagePatterns: [/\bAxis Bank\b/i, /\bAxis\b/i, /Axis Mobile/i, /okaxis/i, /axisbank/i],
    color: '#971237',
    isActive: true,
  },
  {
    id: 'kotak',
    name: 'Kotak Mahindra Bank',
    shortName: 'Kotak',
    senderPatterns: [/KOTAKB/i, /KOTAKK/i, /^KOTAK/i, /-KOTAKB$/i, /[A-Z]{2}-KOTAK/i],
    messagePatterns: [/Kotak Mahindra Bank/i, /Kotak Bank/i, /\bKotak\b/i, /Kotak811/i, /kmbl/i],
    color: '#ED1C24',
    isActive: true,
  },
  {
    id: 'pnb',
    name: 'Punjab National Bank',
    shortName: 'PNB',
    senderPatterns: [/PNBSMS/i, /PNBBK/i, /^PNB/i, /[A-Z]{2}-PNB/i],
    messagePatterns: [/Punjab National Bank/i, /\bPNB\b/i, /PNB ONE/i],
    color: '#A20A3C',
    isActive: true,
  },
  {
    id: 'union',
    name: 'Union Bank of India',
    shortName: 'Union',
    senderPatterns: [/UBINOI/i, /UNIONB/i, /^UNION/i, /[A-Z]{2}-UBI/i, /[A-Z]{2}-UNION/i],
    messagePatterns: [/Union Bank of India/i, /Union Bank/i, /\bVyom\b/i, /\bUBI\b/i],
    color: '#0054A6',
    isActive: true,
  },
  {
    id: 'idfc',
    name: 'IDFC FIRST Bank',
    shortName: 'IDFC FIRST',
    senderPatterns: [/IDFCFB/i, /IDFCBK/i, /^IDFC/i, /[A-Z]{2}-IDFC/i],
    messagePatterns: [/IDFC FIRST Bank/i, /IDFC Bank/i, /\bIDFC\b/i, /idfcbank/i],
    color: '#991B1E',
    isActive: true,
  },
  {
    id: 'indusind',
    name: 'IndusInd Bank',
    shortName: 'IndusInd',
    senderPatterns: [/INDUSB/i, /INDUSI/i, /^INDUS/i, /[A-Z]{2}-INDUS/i],
    messagePatterns: [/IndusInd Bank/i, /\bIndusInd\b/i, /indus/i],
    color: '#65000B',
    isActive: true,
  },
  {
    id: 'federal',
    name: 'Federal Bank',
    shortName: 'Federal',
    senderPatterns: [/FEDBNK/i, /FEDERAL/i, /^FED/i, /[A-Z]{2}-FED/i],
    messagePatterns: [/Federal Bank/i, /\bFederal\b/i, /FedMobile/i],
    color: '#00427A',
    isActive: true,
  },
  {
    id: 'yes',
    name: 'Yes Bank',
    shortName: 'YES',
    senderPatterns: [/YESBNK/i, /YESBANK/i, /^YES/i, /[A-Z]{2}-YES/i],
    messagePatterns: [/Yes Bank/i, /\bYES\b/i, /ybl/i, /yesbank/i],
    color: '#005B9C',
    isActive: true,
  },
  {
    id: 'indian',
    name: 'Indian Bank',
    shortName: 'Indian Bank',
    senderPatterns: [/INDBNK/i, /INDIANB/i, /[A-Z]{2}-IND/i],
    messagePatterns: [/Indian Bank/i, /IndPay/i],
    color: '#003B73',
    isActive: true,
  },
  {
    id: 'boi',
    name: 'Bank of India',
    shortName: 'BOI',
    senderPatterns: [/BOISMS/i, /BOIBNK/i, /[A-Z]{2}-BOI/i],
    messagePatterns: [/Bank of India/i, /\bBOI\b/i, /BOI Mobile/i],
    color: '#E31B23',
    isActive: true,
  },
  {
    id: 'au',
    name: 'AU Small Finance Bank',
    shortName: 'AU Bank',
    senderPatterns: [/AUBANK/i, /AUSFBK/i, /[A-Z]{2}-AU/i],
    messagePatterns: [/AU Small Finance Bank/i, /AU Bank/i, /AU 0101/i],
    color: '#E85F24',
    isActive: true,
  },
  {
    id: 'central',
    name: 'Central Bank of India',
    shortName: 'Central Bank',
    senderPatterns: [/CBIN/i, /CBISMS/i, /CENTBK/i, /[A-Z]{2}-CBI/i],
    messagePatterns: [/Central Bank of India/i, /Cent Mobile/i, /\bCBIN\b/i],
    color: '#005696',
    isActive: true,
  },
  {
    id: 'iob',
    name: 'Indian Overseas Bank',
    shortName: 'IOB',
    senderPatterns: [/IOB/i, /IOBSMS/i, /IOBBNK/i, /[A-Z]{2}-IOB/i],
    messagePatterns: [/Indian Overseas Bank/i, /\bIOB\b/i],
    color: '#004A99',
    isActive: true,
  },
  {
    id: 'uco',
    name: 'UCO Bank',
    shortName: 'UCO',
    senderPatterns: [/UCOBNK/i, /UCOSMS/i, /[A-Z]{2}-UCO/i],
    messagePatterns: [/UCO Bank/i, /\bUCO\b/i, /UCO mBanking/i],
    color: '#004080',
    isActive: true,
  },
  {
    id: 'rbl',
    name: 'RBL Bank',
    shortName: 'RBL',
    senderPatterns: [/RBLBNK/i, /RBLSMS/i, /[A-Z]{2}-RBL/i],
    messagePatterns: [/RBL Bank/i, /\bRBL\b/i, /MoBank/i],
    color: '#002B49',
    isActive: true,
  },
  {
    id: 'karnataka',
    name: 'Karnataka Bank',
    shortName: 'Karnataka Bank',
    senderPatterns: [/KBLTXN/i, /KBLSMS/i, /KBL/i, /[A-Z]{2}-KBL/i],
    messagePatterns: [/Karnataka Bank/i, /KBL Mobile/i, /\bKBL\b/i],
    color: '#C61E2E',
    isActive: true,
  },
  {
    id: 'south_indian',
    name: 'South Indian Bank',
    shortName: 'South Indian Bank',
    senderPatterns: [/SIBLTD/i, /SIBSMS/i, /SIB/i, /[A-Z]{2}-SIB/i],
    messagePatterns: [/South Indian Bank/i, /SIB Mirror/i, /\bSIB\b/i],
    color: '#D42E12',
    isActive: true,
  },
  {
    id: 'karur_vysya',
    name: 'Karur Vysya Bank',
    shortName: 'KVB',
    senderPatterns: [/KVBBANK/i, /KVBSMS/i, /KVB/i, /[A-Z]{2}-KVB/i],
    messagePatterns: [/Karur Vysya Bank/i, /KVB DLX/i, /\bKVB\b/i],
    color: '#ED1B24',
    isActive: true,
  },
  {
    id: 'bandhan',
    name: 'Bandhan Bank',
    shortName: 'Bandhan',
    senderPatterns: [/BNDHN/i, /BNDSMS/i, /[A-Z]{2}-BNDHN/i],
    messagePatterns: [/Bandhan Bank/i, /\bBandhan\b/i],
    color: '#002A54',
    isActive: true,
  },
  {
    id: 'standard_chartered',
    name: 'Standard Chartered Bank',
    shortName: 'StanChart',
    senderPatterns: [/SCBLTD/i, /SCBSMS/i, /SCB/i, /[A-Z]{2}-SCB/i],
    messagePatterns: [/Standard Chartered/i, /\bStanChart\b/i, /\bSCB\b/i],
    color: '#007A3D',
    isActive: true,
  },
  {
    id: 'citibank',
    name: 'Citibank',
    shortName: 'Citi',
    senderPatterns: [/CITIBK/i, /CITISMS/i, /CITI/i, /[A-Z]{2}-CITI/i],
    messagePatterns: [/Citibank/i, /\bCiti\b/i],
    color: '#003B70',
    isActive: true,
  },
  {
    id: 'hsbc',
    name: 'HSBC India',
    shortName: 'HSBC',
    senderPatterns: [/HSBCIN/i, /HSBCSMS/i, /HSBC/i, /[A-Z]{2}-HSBC/i],
    messagePatterns: [/HSBC/i],
    color: '#DB0011',
    isActive: true,
  },
  {
    id: 'dbs',
    name: 'DBS Bank India',
    shortName: 'DBS',
    senderPatterns: [/DBSBNK/i, /DBSSMS/i, /DIGIBK/i, /[A-Z]{2}-DBS/i],
    messagePatterns: [/DBS Bank/i, /digibank/i, /\bDBS\b/i],
    color: '#FF3333',
    isActive: true,
  },
  {
    id: 'paytm',
    name: 'Paytm Payments Bank',
    shortName: 'Paytm Bank',
    senderPatterns: [/PAYTMB/i, /PYTM/i, /PAYTM/i, /[A-Z]{2}-PAYTM/i],
    messagePatterns: [/Paytm Payments Bank/i, /Paytm Bank/i, /Paytm Wallet/i, /@paytm/i],
    color: '#00B9F1',
    isActive: true,
  },
  {
    id: 'airtel',
    name: 'Airtel Payments Bank',
    shortName: 'Airtel Bank',
    senderPatterns: [/AIRBNK/i, /AIRTEL/i, /[A-Z]{2}-AIRTEL/i],
    messagePatterns: [/Airtel Payments Bank/i, /Airtel Money/i, /@airtel/i],
    color: '#ED1C24',
    isActive: true,
  },
  {
    id: 'jio',
    name: 'Jio Payments Bank',
    shortName: 'Jio Payments',
    senderPatterns: [/JIOPAY/i, /JIOBNK/i, /[A-Z]{2}-JIO/i],
    messagePatterns: [/Jio Payments Bank/i, /JioPay/i, /@jio/i],
    color: '#0F288E',
    isActive: true,
  },
  {
    id: 'ippb',
    name: 'India Post Payments Bank',
    shortName: 'IPPB',
    senderPatterns: [/IPPB/i, /POSTBK/i, /[A-Z]{2}-IPPB/i],
    messagePatterns: [/India Post Payments Bank/i, /\bIPPB\b/i, /DakPay/i, /@ippb/i],
    color: '#E31B23',
    isActive: true,
  },
  {
    id: 'jupiter',
    name: 'Jupiter / Federal',
    shortName: 'Jupiter',
    senderPatterns: [/JUPITR/i, /JUPITER/i, /[A-Z]{2}-JUPIT/i],
    messagePatterns: [/\bJupiter\b/i, /@jupiteraxis/i],
    color: '#343A40',
    isActive: true,
  },
  {
    id: 'fi_money',
    name: 'Fi Money / Federal',
    shortName: 'Fi Money',
    senderPatterns: [/FIMONY/i, /FIBANK/i, /[A-Z]{2}-FIMON/i],
    messagePatterns: [/Fi Money/i, /\bFi\b/i, /@fi/i],
    color: '#00C896',
    isActive: true,
  },
];
